config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
   root to: "users#index"

   resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show , :new, :create] do
        resources :comments
        resources :likes
      end
    end

    resources :users, param: :_user_id
    post 'api/v1/auth/login', to: 'authentication#login'

    namespace :api do
      namespace :v1 do
        resources :users, only: [:index] do
          resources :posts, only: [:index , :show] do 
            resources :comments, only: [:index , :show , :create]
          end
        end
    end
   end


    delete 'users/:user_id/posts/:id' , to: 'posts#destroy'
    get 'users/:user_id/posts/:post_id/comments/:id' , to: 'comments#show'
    delete '/users/:user_id/posts/:post_id/comments/:id' , to: 'comments#destroy'
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :authorize_request, except: %i[index]
  before_action :find_user, except: %i[index]

  def index
    @users = User.all

    respond_to do |format|
      format.json { render json: @users }
    end
  end

  def show
    render json: @user, status: :ok
  end

  private

  def find_user
    @user = User.find_by_id!(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { message: 'User not found' }, status: :not_found
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<section class="container">
  <% @users.each do |user| %>
    <div class="user-box">
      <img class="image-user" src=<%= user.photo %> alt="user">
      <div class="user-info">
        <p class="user-name"><%= link_to user.name , user %></p>
        <p class="user-post">Number of posts: <%= user.posts_counter || 0%></p>
      </div>
    </div>
  <% end %>
</section>

app/views/users/show.html.erb
<section class="container">
  <div class="user-box">
    <img class="image-user" src=<%= @user.photo %> alt="user"/>
    <div class="user-info">
      <p class="user-name"><%= @user.name %></p>
      <p class="user-post">Number of posts: <%= @user.posts_counter%></p>
    </div>
  </div>
  <p class="user-bio"><%= @user.bio %></p>
  <% @user.most_recent_post.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id) do %>
      <div class="user-recent-post">
        <p class="post-title"><strong>Post</strong> : <%= post.title %></p>
        <p class="post-text"><%= post.text %></p>
        <h3 class="counters">Comments: <%= post.comments_counter %>
          Likes: <%= post.likes_counter %>
          <h3>
          </div>
        <% end %>
      <% end %>
      <div class="button-user">
        <button class="btn btn-info">
          <%= link_to "See all posts", user_posts_path(@user) %>
        </button>
      </div>
    </section>