config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  
   root to: "users#index"

   resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show , :new, :create] do
        resources :comments
        resources :likes
      end
    end

    resources :users, param: :_user_id
    post 'api/v1/auth/login', to: 'authentication#login'

    namespace :api do
      namespace :v1 do
        resources :users, only: [:index] do
          resources :posts, only: [:index , :show] do 
            resources :comments, only: [:index , :show , :create]
          end
        end
    end
   end


    delete 'users/:user_id/posts/:id' , to: 'posts#destroy'
    get 'users/:user_id/posts/:post_id/comments/:id' , to: 'comments#show'
    delete '/users/:user_id/posts/:post_id/comments/:id' , to: 'comments#destroy'
end 

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :authorize_request
  before_action :find_user

  def index
    user = User.find(params[:user_id])
    posts = user.posts

    if posts.size.positive?
      render json: posts, status: :ok
    else
      render json: { message: 'No posts found' }, status: :not_found
    end
  end

  def show
    @post = @user.posts.find_by_id!(params[:id])
    render json: @post, status: :ok
  rescue ActiveRecord::RecordNotFound
    render json: { message: 'Post not found' }, status: :not_found
  end

  private

  def find_user
    @user = User.find_by_id!(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    render json: { message: 'User not found' }, status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new, alert: 'Post was not created.'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.destroy
    redirect_to user_posts_url(id: @author.id), notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_new_comment.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@post.author, @post), class: "form-control",method: :post do |form| %>
    <div class="mb-3">
      <%= form.label :text , class: "form-label" %>
      <%= form.text_area :text, placeholder: "Type your comment here!", rows: 3, required: true,  class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
    <% end %>

app/views/posts/_new_like.html.erb
<section class="container">
  <%= form_with model: Like , url: user_post_likes_path(@post.author , @post), methodd: :post  do |form| %>
    <%= form.submit 'Add Like', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/posts/index.html.erb
<section class="container">
  <div class="user-box">
    <img class="image-user" src=<%= @user.photo %> alt="user"/>
    <div class="user-info">
      <p class="user-name"><%= @user.name %></p>
      <p class="user-post">Number of posts: <%= @user.posts_counter%></p>
    </div>
  </div>
  <% @posts.each do |post| %>
    <div class="post-info">
      <%= link_to user_post_path(@user.id, post.id) do %>
        <p class="post-title">Post : <%= post.title %> by <%= post.author.name %></p>
        <p class="post-text"><%= post.text %></p>
        <p class="post-text-2">Comments: <span><%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></span></p>
      <% end %>
    </div>
    <div class="comment-info">
      <% post.most_recent_comments.each do |comment| %>
        <p>
          <span>
            <%= comment.author.name %>:
          </span>
          <span>
            <%= comment.text %>
          </span>
        </p>
      <% end %>
    </div>
  <% end %>
  <div class="button-user">
    <%= button_to 'Add New Post', new_user_post_url(id: @user.id), method: :get, class: "btn btn-info"%>
    <button class="btn btn-info">
      Pagination
    </button>
  </div>
</section>

app/views/posts/new.html.erb
<section class="container">
  <p class="post-title">Add New Post :</p>
  <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control" do |form| %>
    <%= form.hidden_field :comments_counter, value: 0 %>
    <%= form.hidden_field :likes_counter, value: 0 %>
    <div class="mb-3 mt-3">
      <%= form.label :title , class: "form-lable" %>
      <%= form.text_field :title, placeholder: "Title", required: true, class: "form-control" %>
    </div>
    <div>
      <%= form.label :text , class: "form-lable"%>
      <%= form.text_area :text, placeholder: "Type your post here!", rows: 5, required: true,  class: "form-control" %>
    </div>
    <div>
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="container">
  <div class="post-info">
    <div class="post-title-box">
      <p class="post-title">Post : <%= @post.title %> by <%= @post.author.name %></p>
     
    </div>
    <p><%= @post.text %></p>
     <p class="comment-text">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
      <% if can? :destroy , @post %>
          <%= button_to 'Delete', user_post_path(@user , @post), method: :delete, class: "btn btn-danger" %>
        <%end%>
  </div>
  <div class="comment-info">
    <% @post.most_recent_comments.each do |comment| %>
      <div>
        <p>
          <span>
            <%= comment.author.name %>:
          </span>
          <span>
            <%= comment.text %>
          </span>
        </p>
      </div> 
      <% if can? :destroy , comment %>
        <%= button_to "Delete Comment" , user_post_comment_path(@user , @post , comment) , method: :delete , class: "btn btn-danger" %>
      <%end%>
    <% end %>
    <%= render 'new_comment', post: @post %>
    <div class="like-btn"> 
      <%= render 'new_like' , post: @post %>
    </div> 
  </div>

</section>